#!/usr/bin/env python3

import matplotlib.pyplot as plt
import os




for file_name in os.listdir('charts/'):
    csv = open('charts/' + file_name, 'r')
    series1 = []
    series2 = []
    series3 = []

    for line in csv:
        tab = line.split(',')
        series1.append(tab[0])
        series2.append(tab[1])
        series3.append(tab[2])

    # series1.reverse()
    # series2.reverse()
    # series3.reverse()

    plt.plot(range(1,101), series1, 'r')
    plt.plot(range(1,101), series2, 'b')
    plt.plot(range(1,101), series3, 'g')
    plt.title(file_name)
    plt.show()
    # plt.savefig(file_name[:-3] + '.pdf')
    # plt.close()
